#!/bin/bash

if [ $# -lt 3 ]; then
    echo "Usage: $0 [-v] [-p program] <from> <to>"
    exit 1
fi

program=""
from=""
to=""
verbose=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -p)
            program="$2"
            shift 2
            ;;
        -v)
            verbose=true
            shift
            ;;
        *)
            if [ -z "$from" ]; then
                from="$1"
            elif [ -z "$to" ]; then
                to="$1"
            else
                echo "Error: Too many arguments"
                exit 1
            fi
            shift
            ;;
    esac
done

if [ -z "$from" ] || [ -z "$to" ]; then
    echo "Error: Both 'from' and 'to' arguments are required"
    exit 1
fi

if [ -n "$program" ]; then
    case $program in
        java)
            file_pattern="*.java"
            ;;
        python)
            file_pattern="*.py"
            ;;
        go)
            file_pattern="*.go"
            ;;
        *)
            echo "Error: Unsupported program type"
            exit 1
            ;;
    esac
else
    file_pattern="*"
fi

if [ "$verbose" = true ]; then
    find . -type f -name "$file_pattern" -print0 | xargs -0 sed -i -n "s/$from/$to/gIp"
else
    find . -type f -name "$file_pattern" -print0 | xargs -0 sed -i "s/$from/$to/gI"
fi

echo "Replacement completed successfully."
